### ISSUE TITLE
Getting error when compiling

### ISSUE THREAD

**Issue by shayanhusaini** [maiyaporn/angular2-wizard#1]
Hi,
I am getting following error when compiling your library:
Type `EventEmitter<{}>` is not assignable to type `EventEmitter<WizardStepComponent>`.

After a brief look into your code I found that line 41 in your wizard.component.ts file should be like this:
`@Output() onStepChanged: EventEmitter<WizardStepComponent> = new EventEmitter<WizardStepComponent>();`

Instead of this:
`@Output() onStepChanged: EventEmitter<WizardStepComponent> = new EventEmitter();`

Please update your code ASAP.

**Comment by maiyaporn** [comment]
Thanks for pointing this out. However, I am unable to reproduce this error on my local machine.
Can you share which version of typescript you are using?

Upgrading to a newer version should resolve the issue. I will also update the code.
