### ISSUE TITLE
Doesn't work with AOT, gives private property error

### ISSUE THREAD

**Issue by rushi216** [maiyaporn/angular2-wizard#16]
It works with JIT, but when using AOT compilation it gives error "Property 'steps' is private and only accessible within class 'WizardComponent'"

Full error details:

Property 'steps' is private and only accessible within class 'WizardComponent'.
Property 'isCompleted' is private and only accessible within class 'WizardComponent'.
Property 'hasPrevStep' is private and only accessible within class 'WizardComponent'.
Property 'activeStep' is private and only accessible within class 'WizardComponent'.
Property 'hasNextStep' is private and only accessible within class 'WizardComponent'.

**Comment by jackjamieson** [comment]
I believe this is the associated Angular CLI issue https://github.com/angular/angular-cli/issues/5623.

Properties need to be public if they are accessed within the template.

**Comment by rustamguseynov** [comment]
Any updates?

**Comment by dennisholmer** [comment]
+1
