### ISSUE TITLE
npm package still has old distribution files

### ISSUE THREAD

**Issue by bcrigler** [maiyaporn/angular2-wizard#22]
So I can see you removed "private" off of some of the methods in here which makes sense and was causing errors when running `ng build --prod` using angular-cli.  Although even after reinstalling all the packages and clearing npm cache the source is not up to date with the repo here as it's still showing those private declarations on the methods.  Think you need to update the npm package as well with this change because I'm having to manually remove them.

![screen shot 2017-06-15 at 3 45 47 pm](https://user-images.githubusercontent.com/2781424/27198814-d02d8c72-51e1-11e7-8b2b-7b2f55cdc3da.png)
![screen shot 2017-06-15 at 3 46 03 pm](https://user-images.githubusercontent.com/2781424/27198815-d030cd92-51e1-11e7-8ebd-8a006bb39666.png)

**Comment by maiyaporn** [comment]
Sorry for that. I was going to update the package, but was caught up with something else. Anyway, the package is updated now. The latest version is [0.4.0](https://github.com/maiyaporn/angular2-wizard/releases/tag/v0.4.0).
