### ISSUE TITLE
404 Not Found loading http://localhost:3000/angular2-wizard

### ISSUE THREAD

**Issue by ckng** [maiyaporn/angular2-wizard#28]
Getting error
`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/angular2-wizard`

Steps to reproduce:
```
$ git clone https://github.com/angular/quickstart.git quickstart-wizard; cd quickstart-wizard
$ npm install
$ npm install angular2-wizard --save

```
Update app.module.ts per documentation, paste example into app.component.ts as template.

**Comment by gschambial** [comment]
@ckng did you find any solution? I am also facing this issue.

**Comment by ckng** [comment]
This turns out to be the quickstart repo issue. Did not dig what's wrong or the differences. Have switched to use angular-cli.

**Comment by gschambial** [comment]
Ok, Thanks for response though.
