### ISSUE TITLE
dynamic loading

### ISSUE THREAD

**Issue by yfreedman** [maiyaporn/angular2-wizard#3]
Are you working on adding the ability to load steps dynamically at runtime?

**Comment by maiyaporn** [comment]
I am planning to work on this feature soon, but haven't started yet. If you have any suggestion or solution, please feel free to share or create PR.

**Comment by maiyaporn** [comment]
I have published the new version that supports the ability to dynamically show/hide the step. Not sure if this is what you want, but you can check it out here [my demo] (http's: //maiyaporn.github.io/angular2-wizard-demo/) - step3. There is a hidden step (step3.5) that will be visible when you check the checkbox on step3.

Basically, you need to define all the possible steps in the component template and control which one you want to show or hide by using [hidden] property on the wizard-step. I haven't updated the document, but you can take a look at the code in the demo.

I'm still figuring out how to accomplish the same thing from the component class.

Let me know if this doesn't work for you and it would be great if you can share the detail of your work.

**Comment by yfreedman** [comment]
I like what you did. I need to create all the steps dynamically, though, so it will be more complex. Thanks for the update!

**Comment by matheo** [comment]
@yfreedman Hey
Have you figured out a nice way to handle that?
I'm having issues bundling the App for `-prod`, dynamic components are not included in the final bundle but I'm debugging that right now, I might share my "wizard framework" soon, have you some stuff for inspiration?
Thank you @maiyaporn for this!
