### ISSUE TITLE
How to customize appearance

### ISSUE THREAD

**Issue by chris93007** [maiyaporn/angular2-wizard#4]
How can add my own scss to this the wizard?
And class I apply isn't being applied

**Comment by matheo** [comment]
This is an advanced topic of Angular Components:
https://angular.io/docs/ts/latest/guide/component-styles.html
I will have to dig in this one to modify a library's CSS

**Comment by 02harleen** [comment]
How can add own css and own design to this the wizard?

**Comment by maiyaporn** [comment]
You can try to use [/deep/ ](https://angular.io/guide/component-styles#deep) to override the styling of the wizard.
