### ISSUE TITLE
Can we use another button click to move to next step. Instead of clicking on the next button at the bottom?

### ISSUE THREAD

**Issue by sanuradhag** [maiyaporn/angular2-wizard#8]

**Comment by maiyaporn** [comment]
Right now, there are only two ways to navigate btw step
- Next/Prev button
- Title

There is no public method you can call to change the step at this time. Feel feel to create a PR if you have a solution.

**Comment by sanuradhag** [comment]
next(), previous() are public methods. So by using a local variable (#form-wizard), I can call those two methods when ever I want.. And that is working fine.
Thanks

**Comment by maiyaporn** [comment]
Thanks for the update. I guess I'm starting to forget my own code after I'm away for a few weeks. Haha
