### ISSUE TITLE
Issue arrives while installing using gitbash

### ISSUE THREAD

**Issue by sonalien** [maiyaporn/angular2-wizard#9]
DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

$ npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\angular\ng2-wizard-master\ng2\angular2-wizard\npm-debug.log

**Comment by matheo** [comment]
This repository is intended to be used as a library,
if you want to run a demo you should try this one:
https://github.com/maiyaporn/angular2-wizard-demo
```
npm install
npm start
```
Greetings

**Comment by maiyaporn** [comment]
Thanks @matheo for answering this.

**Comment by matheo** [comment]
@maiyaporn Thanks to you for this lib, as soon as I have time I will share my approach with Dynamic Components, even if they doesn't load in production with the latest CLI build function yet hehe
